import type { MetaAnalysisResult, EggersTest, BeggsTest, SubgroupAnalysisResult, SensitivityResult, PICO, MetaRegressionResult, GradeAssessment, InfluenceDiagnostic, RobAssessments, RobDomain, Study, CumulativeResult } from './types';
import type { TrimAndFillResult } from './statistics/publication-bias';
import type { ReportSections } from './report-export';
import { defaultReportSections } from './report-export';
import { calculateNNT } from './statistics/nnt';
import { isLogScale } from './statistics';

interface MarkdownReportData {
  title: string;
  pico: PICO;
  result: MetaAnalysisResult;
  eggers: EggersTest | null;
  beggs?: BeggsTest | null;
  subgroupResult: SubgroupAnalysisResult | null;
  sensitivityResults: SensitivityResult[];
  trimFillResult?: TrimAndFillResult | null;
  metaRegression?: MetaRegressionResult | null;
  influenceDiagnostics?: InfluenceDiagnostic[];
  gradeAssessment?: GradeAssessment | null;
  robAssessments?: RobAssessments;
  studies?: Study[];
  cumulativeResults?: CumulativeResult[];
  sections?: ReportSections;
}

const fmt = (n: number, d = 2) => n.toFixed(d);
const fmtP = (p: number) => p < 0.001 ? '< 0.001' : p.toFixed(3);

export function generateReportMarkdown(data: MarkdownReportData): string {
  const { result, eggers, beggs, subgroupResult, sensitivityResults, trimFillResult, metaRegression, influenceDiagnostics, gradeAssessment, robAssessments, studies, cumulativeResults } = data;
  const sec = data.sections || defaultReportSections;
  const measure = result.measure;
  const log = isLogScale(measure);
  const lines: string[] = [];

  lines.push(`# ${data.title || 'Meta-Analysis Report'}`);
  lines.push(`\n*Generated by MetaReview (https://metareview.cc) — ${new Date().toISOString().split('T')[0]}*\n`);

  // PICO
  if (sec.pico && (data.pico.population || data.pico.intervention)) {
    lines.push('## PICO\n');
    lines.push(`| Component | Description |`);
    lines.push(`|-----------|-------------|`);
    if (data.pico.population) lines.push(`| **Population** | ${data.pico.population} |`);
    if (data.pico.intervention) lines.push(`| **Intervention** | ${data.pico.intervention} |`);
    if (data.pico.comparison) lines.push(`| **Comparison** | ${data.pico.comparison} |`);
    if (data.pico.outcome) lines.push(`| **Outcome** | ${data.pico.outcome} |`);
    lines.push('');
  }

  // Overall results
  if (sec.overall) {
    lines.push('## Overall Results\n');
    const r = result;
    const nullVal = log ? 1 : 0;
    lines.push(`- **Effect measure**: ${measure}`);
    lines.push(`- **Model**: ${r.model === 'fixed' ? 'Fixed-effects' : 'Random-effects (DerSimonian-Laird)'}`);
    lines.push(`- **Number of studies**: ${r.studies.length}`);
    lines.push(`- **Pooled estimate**: ${fmt(r.overall)} (95% CI: ${fmt(r.ciLower)}–${fmt(r.ciUpper)})`);
    lines.push(`- **p-value**: ${fmtP(r.pValue)}`);
    lines.push(`- **Heterogeneity**: Q = ${fmt(r.Q)}, df = ${r.studies.length - 1}, p = ${fmtP(r.Qp)}`);
    lines.push(`- **I²**: ${fmt(r.I2, 1)}%`);
    lines.push(`- **τ²**: ${fmt(r.tau2, 4)}`);
    if (r.predictionInterval) {
      lines.push(`- **Prediction interval**: ${fmt(r.predictionInterval[0])}–${fmt(r.predictionInterval[1])}`);
    }

    // NNT/NNH
    if (studies) {
      const nnt = calculateNNT(r, studies);
      if (nnt) {
        lines.push(`- **${nnt.isHarm ? 'NNH' : 'NNT'}**: ${fmt(nnt.nnt, 1)} (95% CI: ${nnt.ciLower === Infinity ? '∞' : fmt(nnt.ciLower, 1)}–${nnt.ciUpper === Infinity ? '∞' : fmt(nnt.ciUpper, 1)})`);
      }
    }

    lines.push('');

    // Interpretation
    if (sec.interpretation) {
      const direction = r.overall > nullVal ? 'higher' : 'lower';
      const sig = r.pValue < 0.05 ? 'statistically significant' : 'not statistically significant';
      lines.push(`**Interpretation**: The pooled ${measure} is ${fmt(r.overall)} (95% CI: ${fmt(r.ciLower)}–${fmt(r.ciUpper)}), which is ${sig} (p = ${fmtP(r.pValue)}). The point estimate suggests a ${direction} effect in the intervention group. Heterogeneity is ${r.I2 < 25 ? 'low' : r.I2 < 75 ? 'moderate' : 'high'} (I² = ${fmt(r.I2, 1)}%).\n`);
    }
  }

  // Study table
  if (sec.studyTable && result.studies.length > 0) {
    lines.push('## Individual Studies\n');
    lines.push(`| Study | ${measure} | 95% CI | Weight |`);
    lines.push(`|-------|${'-'.repeat(measure.length + 2)}|--------|--------|`);
    for (const s of result.studies) {
      lines.push(`| ${s.name} | ${fmt(s.yi)} | ${fmt(s.ciLower)}–${fmt(s.ciUpper)} | ${fmt(s.weight, 1)}% |`);
    }
    lines.push('');
  }

  // Publication bias
  if ((sec.eggers && eggers) || (sec.beggs && beggs)) {
    lines.push('## Publication Bias\n');
    if (eggers) {
      lines.push(`- **Egger's test**: intercept = ${fmt(eggers.intercept, 3)}, t = ${fmt(eggers.t, 3)}, p = ${fmtP(eggers.p)}`);
      lines.push(`  - ${eggers.p < 0.05 ? '⚠️ Significant asymmetry detected' : 'No significant asymmetry'}`);
    }
    if (beggs) {
      lines.push(`- **Begg's test**: τ = ${fmt(beggs.tau, 3)}, p = ${fmtP(beggs.p)}`);
    }
    if (trimFillResult && trimFillResult.k0 > 0) {
      lines.push(`- **Trim-and-Fill**: ${trimFillResult.k0} imputed studies, adjusted estimate = ${fmt(trimFillResult.overall)}`);
    }
    lines.push('');
  }

  // Subgroup analysis
  if (sec.subgroup && subgroupResult) {
    lines.push('## Subgroup Analysis\n');
    lines.push(`Grouping variable: ${subgroupResult.variable}\n`);
    lines.push(`| Subgroup | k | ${measure} | 95% CI | I² |`);
    lines.push(`|----------|---|${'-'.repeat(measure.length + 2)}|--------|-----|`);
    for (const g of subgroupResult.groups) {
      lines.push(`| ${g.name} | ${g.k} | ${fmt(g.overall)} | ${fmt(g.ciLower)}–${fmt(g.ciUpper)} | ${fmt(g.I2, 1)}% |`);
    }
    if (subgroupResult.interactionP != null) {
      lines.push(`\nInteraction test: Q = ${fmt(subgroupResult.interactionQ)}, p = ${fmtP(subgroupResult.interactionP)}`);
    }
    lines.push('');
  }

  // Sensitivity analysis
  if (sec.sensitivity && sensitivityResults.length > 0) {
    lines.push('## Sensitivity Analysis (Leave-One-Out)\n');
    lines.push(`| Omitted | ${measure} | 95% CI | I² |`);
    lines.push(`|---------|${'-'.repeat(measure.length + 2)}|--------|-----|`);
    for (const s of sensitivityResults) {
      lines.push(`| ${s.omittedStudy} | ${fmt(s.overall)} | ${fmt(s.ciLower)}–${fmt(s.ciUpper)} | ${fmt(s.I2, 1)}% |`);
    }
    lines.push('');
  }

  // Meta-regression
  if (sec.metaReg && metaRegression) {
    lines.push('## Meta-Regression\n');
    lines.push(`- **Covariate**: ${metaRegression.covariate}`);
    lines.push(`- **Intercept**: ${fmt(metaRegression.intercept, 4)}`);
    lines.push(`- **Slope**: ${fmt(metaRegression.slope, 4)}`);
    lines.push(`- **p-value**: ${fmtP(metaRegression.p)}`);
    lines.push(`- **R²**: ${fmt((metaRegression.R2 ?? 0) * 100, 1)}%`);
    lines.push('');
  }

  // Influence diagnostics
  if (sec.influence && influenceDiagnostics && influenceDiagnostics.length > 0) {
    lines.push('## Influence Diagnostics\n');
    const influential = influenceDiagnostics.filter(d => d.isInfluential);
    if (influential.length > 0) {
      lines.push(`**Potentially influential studies**: ${influential.map(d => d.studyName).join(', ')}\n`);
    } else {
      lines.push('No individually influential studies detected.\n');
    }
  }

  // GRADE
  if (sec.grade && gradeAssessment) {
    lines.push('## GRADE Assessment\n');
    lines.push(`**Overall certainty**: ${gradeAssessment.overall.toUpperCase()}\n`);
    lines.push(`| Domain | Rating | Reason |`);
    lines.push(`|--------|--------|--------|`);
    for (const d of gradeAssessment.domains) {
      lines.push(`| ${d.domain} | ${d.rating} | ${d.reason || '—'} |`);
    }
    lines.push('');
  }

  // RoB
  if (sec.rob && robAssessments && Object.keys(robAssessments).length > 0) {
    lines.push('## Risk of Bias\n');
    const DOMAINS: RobDomain[] = ['D1', 'D2', 'D3', 'D4', 'D5'];
    const DOMAIN_LABELS: Record<RobDomain, string> = {
      D1: 'Randomization', D2: 'Deviations', D3: 'Missing data', D4: 'Measurement', D5: 'Selection',
    };
    lines.push(`| Study | ${DOMAINS.map(d => DOMAIN_LABELS[d]).join(' | ')} | Overall |`);
    lines.push(`|-------|${DOMAINS.map(() => '---').join('|')}|---------|`);
    for (const [study, assessment] of Object.entries(robAssessments)) {
      const cells = DOMAINS.map(d => assessment.domains[d] || '—');
      lines.push(`| ${study} | ${cells.join(' | ')} | ${assessment.overall} |`);
    }
    lines.push('');
  }

  // Cumulative
  if (sec.cumulative && cumulativeResults && cumulativeResults.length > 0) {
    lines.push('## Cumulative Meta-Analysis\n');
    lines.push(`| Added Study | ${measure} | 95% CI |`);
    lines.push(`|-------------|${'-'.repeat(measure.length + 2)}|--------|`);
    for (const c of cumulativeResults) {
      lines.push(`| ${c.addedStudy} | ${fmt(c.overall)} | ${fmt(c.ciLower)}–${fmt(c.ciUpper)} |`);
    }
    lines.push('');
  }

  // Methods
  if (sec.methods) {
    lines.push('## Methods\n');
    lines.push(`This meta-analysis was conducted using MetaReview (https://metareview.cc). ${result.model === 'random' ? 'Random-effects model with DerSimonian-Laird estimator' : 'Fixed-effects model (inverse-variance method)'} was used. Effect sizes are reported as ${measure} with 95% confidence intervals. Heterogeneity was assessed using Cochran's Q test and the I² statistic.`);
    lines.push('');
  }

  lines.push('---\n');
  lines.push('*Note: Plots (forest plot, funnel plot, etc.) are available in the HTML export.*');

  return lines.join('\n');
}
